import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import '../styles/global.scss'
import ClientProvider from '@/modules/ClientProvider'
import {SearchProvider} from './context/SearchContext'
import Header from '@/modules/header/Header'
import Footer from '@/modules/footer/Footer'
import Head from 'next/head'

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
  title: 'Free Stock Photos',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <Head>
        <link rel='icon' href='/favicon.ico' />
        <link rel='icon' type='image/png' href='/favicon.png' />
      </Head>
      <body className={inter.className}>
        <ClientProvider>
          <SearchProvider>
            <Header />
            {children}
            <Footer />
          </SearchProvider>
        </ClientProvider>
      </body>
    </html>
  )
}
